language: node_js

node_js:
  - 0.12
before_script:
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - bower install
script:
  - npm run travis
after_script:
  - codeclimate < coverage/**/lcov.info